### ISSUE TITLE
CodeMirror embedded

### ISSUE THREAD

**Issue by franck-paul** [Gvx-/dcScript#2]
Pourquoi transporter ta propre version de CodeMirror plutôt que d'utiliser celle fournie avec Dotclear, comme le fait par exemple le plugin themeEditor ?

**Comment by Gvx-** [comment]
Car il manque des addons dans celle fourni par dotclear.

si je n'ajoute que les addons, il y risque incompatibilité, si la version de dotclear évolue et pas celle du plugin.

**Comment by franck-paul** [comment]
Ah ok, ça m'intéresse toujours de savoir ce genre de détail. Je vais regarder ce que tu utilises comme addons par rapport à ce qu'il y a dans Dotclear.

Merci pour la réponse !
